### ISSUE TITLE
Took long time to run the benchmarking code

### ISSUE THREAD

**Issue by jpzhangvincent** [Mcompetitions/M5-methods#2]
Just curious, how long did it take to run the benchmarking code (assuming it's running in parallel)?

I have been trying to run the code on my Mac Desktop(12cores, 30G Memory) but it's been running almost a day.

**Comment by ErikEngerd** [comment]
hi,

I have tried to run this as well but simply aborted after more than 24 hours. Perhaps it is good if the result files were posted somewhere.

cheers
  Erik

On 18 April 2020 07:56:27 CEST, "Jiaping(JP) Zhang" <notifications@github.com> wrote:
>Just curious, how long did it take to run the benchmarking code
>(assuming it's running in parallel)?
>
>I have been trying to run the code on my Mac Desktop(12cores, 30G
>Memory) but it's been running almost a day.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/Mcompetitions/M5-methods/issues/2

Erik Brakkee

**Comment by Mcompetitions** [comment]
We are sorry for the inconvenience. The results of the benchmarks are now published
