### ISSUE TITLE
may you tell us, when winning code will be published in this repo or other place? 

### ISSUE THREAD

**Issue by Sandy4321** [Mcompetitions/M5-methods#5]
may you tell us, when winning code will be published in this repo or other place? 

as it is written in https://mofc.unic.ac.cy/m5-competition/
Reproducibility
The prerequisite for winning any prize will be that the code used for generating the forecasts, with the exception of companies providing forecasting services and those claiming proprietary software, will be put on GitHub, not later than 14 days after the end of the competition (i.e., the 14th of July, 2020).

**Comment by sndrstpnv** [comment]
any answer pls?

**Comment by MaxHalford** [comment]
A lot of the top scoring solutions from the Kaggle competitions discuss their solution on the [relevant Kaggle discussion section](https://www.kaggle.com/c/m5-forecasting-accuracy/discussion). For instance, here is the [1st place solution](https://www.kaggle.com/c/m5-forecasting-accuracy/discussion/163684).

**Comment by Sandy4321** [comment]
as I remember you promised to publish winners code?
can you do it?

**Comment by Mcompetitions** [comment]
We'll be publishing the code of the top-5 performing methods here as soon as the final ranks are officially announced and the codes provided have been fully reproduced.
Till then, Kaggle discussions can be used for getting an overview of these solutions
