### ISSUE TITLE
"This repository is over its data quota." error

### ISSUE THREAD

**Issue by FedericoGarza** [Mcompetitions/M5-methods#8]
Hi! 

I'm trying to clone the repo to reproduce the results; I'm using `git lfs clone` but I get the following error.
Any suggestions on how to fix it?

![image](https://user-images.githubusercontent.com/10517170/95391890-7635a380-08bd-11eb-896d-c78054b9c298.png)

**Comment by rquintino** [comment]
same thing here, unable to get any data file :(

**Comment by MMencheroG** [comment]
Same. Seems this problem persists...

**Comment by HansikaPH** [comment]
I am experiencing the same issue

**Comment by shaheenahmedc** [comment]
Myself also, has anyone had any contact with the M5 team?

**Comment by HansikaPH** [comment]
The required files are available at the Google Drive link mentioned on the Readme.

**Comment by Mcompetitions** [comment]
The M5 data set and submissions can be found in the following link.
https://drive.google.com/drive/folders/1D6EWdVSaOtrP1LEFh1REjI3vej6iUS_4?usp=sharing
We are going to keep to keep on GitHub only the code used by the organizers and winners.

**Comment by rquintino** [comment]
much thanks @Mcompetitions @HansikaPH   didn't catch that note, just downloaded, thanks!
